window_width 1440
window_height 920

start_pos -1e9
amount_of_nodes 220
default_height_of_the_grid -7.f

camera_fov 45.f
camera_target 0.f 0.f 0.f
camera_position 100.f 100.f 100.f
camera_up 0.f 1.f 0.f

distance_divider 3e6
radius_divider 1e4